spring:
  application:
    name: sp-ai
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:nacos:8848}
      config:
        server-addr: ${NACOS_ADDR:nacos:8848}
        username: nacos
        password: ${NACOS_PASSWORD}
        file-extension: yaml
      discovery:
        server-addr: ${NACOS_ADDR:nacos:8848}
        username: nacos
        password: ${NACOS_PASSWORD}
  config:
    import:
      - nacos:sp-ai.yaml
